// Mood seeds — randomly sampled when no user prompt is provided
export const MOODS = [
  // Warm / cozy
  'warm and inviting, like a cozy bookshop',
  'fireside warmth, aged leather and amber glow',
  'autumn harvest, burnt sienna and golden wheat',
  'Tuscan villa, warm stone and olive groves',
  'hygge living room, soft wool and candlelight',
  'old library, mahogany shelves and brass lamps',
  'grandma\'s kitchen, warm yellow and worn wood',
  'cabin in the woods, pine green and wool gray',
  'candlelit dinner, warm amber and deep red',
  'bakery morning, warm cream and golden crust',
  'cinnamon and chai, spiced warmth on ivory',
  'worn leather journal, coffee-stained pages',

  // Cool / minimal
  'clean and airy, Scandinavian minimalism',
  'stark and modern, Japanese minimalism',
  'crisp and cool, arctic whites and steel blue',
  'Swiss design, precise grids and Helvetica spirit',
  'zen garden, raked sand and moss green',
  'moonlit snow, silver and ice blue',
  'white gallery, one accent color on pure white',
  'fog and glass, frosted transparency and soft edges',
  'paper and pencil, sketch-like minimalism',
  'cloud nine, soft white and pale silver',
  'ice hotel, translucent blue and white',
  'morning dew, crystal clear and fresh green',

  // Earthy / natural
  'earthy and grounded, terracotta and olive',
  'sun-baked, desert sand and turquoise',
  'lush and verdant, deep forest greens',
  'Pacific Northwest, misty greens and slate',
  'Mediterranean coast, whitewash and cobalt blue',
  'alpine meadow, wildflower colors on cream',
  'volcanic island, black sand and tropical green',
  'moss and stone, damp forest floor',
  'bamboo grove, pale green and natural tan',
  'river stones, smooth gray and water blue',
  'savanna at dusk, golden grass and warm sky',
  'coral reef, underwater blues and living coral',
  'redwood forest, deep brown bark and fern green',
  'prairie wind, wheat gold and sky blue',
  'mushroom foraging, earthy brown and forest cream',
  'desert oasis, sand dune gold and palm green',
  'salt flats, blinding white and pale blue sky',
  'pebble beach, warm gray stones and seafoam',

  // Editorial / bold
  'bold editorial, like a fashion magazine',
  'classic newspaper, black and white with one pop color',
  'brutalist architecture, raw concrete and sharp angles',
  'art deco, gold and geometric patterns',
  'Bauhaus, primary colors and clean geometry',
  'punk zine, high contrast and raw energy',
  'Swiss poster, bold sans-serif and structured grid',
  'Russian constructivism, red and black on cream',
  'De Stijl, Mondrian primary blocks',
  'typography specimen, oversized letters and ink black',
  'woodblock print, bold lines and flat color',
  'silkscreen poster, limited palette and bold shapes',

  // Soft / romantic
  'soft and romantic, lavender and plum',
  'golden hour, sunset peach and amber',
  'cherry blossom, pale pink and soft gray',
  'watercolor painting, soft washes and muted tones',
  'French patisserie, cream and rose',
  'morning fog, soft grays and pale blue',
  'dried flowers, muted mauve and sage',
  'ballet studio, blush pink and warm wood',
  'rose garden, dusty pink and deep green',
  'silk and pearl, ivory and soft champagne',
  'love letter, parchment and ink',
  'pressed flowers, faded botanicals on cream',

  // Oceanic / aquatic
  'oceanic, coastal blues and corals',
  'deep sea, navy and bioluminescent accents',
  'tropical lagoon, turquoise and white sand',
  'stormy coast, charcoal skies and seafoam',
  'tidepools, jade green and wet stone',
  'sailing yacht, navy and crisp white',
  'frozen lake, pale ice blue and silver',
  'kelp forest, deep green and filtered sunlight',
  'Caribbean breeze, aqua and sun-bleached white',
  'lighthouse at dawn, steel gray and warm lantern',

  // Playful / vibrant
  'playful and sweet, candy pastels',
  'retro arcade, pixel art neon on dark',
  'Memphis design, squiggles and bold shapes',
  'pop art, Warhol-inspired bold colors',
  'carnival, bright stripes and warm yellow',
  'bubblegum and skateparks, Y2K nostalgia',
  'ice cream parlor, pastel rainbow and chrome',
  'crayon box, bright primary on white paper',
  'confetti celebration, multicolor on white',
  'toy store window, bright plastic and joy',
  'gummy bears, translucent candy colors',
  'roller disco, purple and electric pink',

  // Refined / luxury
  'refined luxury, old money elegance',
  'aged and textured, vintage paper and sepia',
  'royal court, deep purple and gold leaf',
  'jazz club, midnight blue and warm brass',
  'wine cellar, deep burgundy and oak',
  'black tie gala, charcoal and champagne gold',
  'private library, hunter green and gilt',
  'marble and gold, Carrara white and warm metal',
  'opera house, crimson velvet and ivory',
  'antique shop, patina green and aged brass',
  'whisky lounge, amber and dark walnut',
  'silk kimono, rich indigo and gold thread',

  // Cultural / geographic
  'Moroccan riad, tiles and warm spice colors',
  'Nordic fjord, deep blue and lichen green',
  'Kyoto temple, vermillion and dark wood',
  'Havana street, faded pastels and warm sun',
  'Greek island, white and cerulean',
  'Indian summer, saffron and deep teal',
  'Scottish highlands, heather purple and mossy green',
  'Parisian café, charcoal and butter cream',
  'Venetian palazzo, faded terracotta and canal blue',
  'Istanbul bazaar, jewel tones and warm copper',
  'Saharan caravan, deep ochre and indigo',
  'Bangkok temple, gold and deep red',
  'New England autumn, crimson and cream',
  'Lisbon azulejo, tile blue and warm white',
  'Balinese spa, bamboo and frangipani white',
  'Oaxacan craft, burnt orange and deep purple',
  'Amsterdam canal house, dark green and warm brick',
  'Icelandic hot spring, mineral blue and volcanic gray',

  // Seasons / time
  'spring morning, fresh green and soft yellow',
  'midsummer night, deep indigo and firefly gold',
  'October twilight, amber and dusty purple',
  'winter solstice, deep blue and silver frost',
  'golden autumn, maple red and warm brown',
  'rainy afternoon, soft gray and warm tea',
  'summer lemonade, bright yellow and white',
  'first snow, soft white and bare branch gray',
  'April showers, pale blue and lilac',
  'harvest moon, deep orange and midnight blue',
  'crisp November, brown and smoky gray',
  'June garden, green and blooming rose',

  // Materials / textures
  'raw linen, natural beige and soft texture',
  'copper and sage, metallic warmth and muted green',
  'concrete and glass, brutalist gray and sharp light',
  'hand-dyed indigo, shibori blue and natural white',
  'washi paper, soft cream and ink',
  'oxidized metal, verdigris green and dark bronze',
  'terra sigillata, polished clay red and black',
  'reclaimed wood, warm grain and iron nails',
  'Japanese lacquerware, deep black and vermillion',
  'woven rattan, honey gold and shadow brown',

  // Art / design movements
  'impressionist garden, dappled light and soft color',
  'art nouveau, organic curves and muted gold',
  'gothic cathedral, stone gray and stained glass jewels',
  'mid-century modern, teak and burnt orange',
  'vaporwave, pastel pink and cyan on soft purple',
  'cottagecore, floral cream and sage green',
  'dark academia, tweed brown and forest green',
  'solarpunk, bright green and warm gold on cream',
  'steampunk, brass and aged leather on dark',
  'ukiyo-e woodblock, indigo and cherry on cream',

  // Misc vibes
  'space observatory, dark with starlight accents',
  'botanical illustration, cream and ink green',
  'apothecary shop, amber glass and dried herbs',
  'ceramics studio, clay and glaze blue',
  'darkroom photography, red safelight on black',
  'linen and ink, natural textures and sharp type',
  'vinyl record shop, warm black and orange label',
  'planetarium, deep navy and projected star white',
  'greenhouse, humid green and iron frame',
  'old map, parchment and faded cartography ink',
  'typewriter, cream paper and ribbon black',
  'stationery shop, kraft paper and colored pencil',
  'film noir, high contrast black and silver',
  'waterfront warehouse, industrial gray and harbor blue',
  'sundial garden, warm stone and herb green',
  'mountain summit, crisp air blue and granite',
  'calligraphy studio, rice paper and sumi ink',
  'terrarium, glass and miniature green',
];

// Pick n random unique items from an array
const sample = (arr, n) => {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(n, arr.length));
};

export const buildRandomPrompt = () => {
  const picks = sample(MOODS, 10);
  return `Here are some mood ideas for inspiration — pick ONE that excites you and interpret it freely:\n${picks.map((m, i) => `${i + 1}. ${m}`).join('\n')}\n\nSurprise me with your interpretation. Be bold and creative.`;
};
